### PR TITLE
Fix `null` and `undefined` string handling

### PR DESCRIPTION
**Pull request by dwick**
:eyeglasses: @ajacksified @madbook

### CODE REVIEW

**Comment by dwick** [comment]
```js
null.toString()
VM131:2 Uncaught TypeError: Cannot read property 'toString' of null
undefined.toString()
VM153:2 Uncaught TypeError: Cannot read property 'toString' of undefined
```

and

```
TypeError: Cannot call method 'substring' of undefined
    at Parameter.format (/vagrant/node_modules/metron/src/parameter.js:90:25)
    at new Parameter (/vagrant/node_modules/metron/src/parameter.js:56:8)
    at Metron.processParameters (/vagrant/node_modules/metron/src/metron.js:159:18)
    at Metron.<anonymous> (/vagrant/node_modules/metron/src/metron.js:79:12)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by madbook** [comment]
does this catch the `undefined` case?

**Comment by madbook** [comment]
:nail_care:

**Comment by dwick** [comment]
:haircut: `x == null` === `x === null || x === undefined` it's covered by jshint's: [eqnull](http://jshint.com/docs/options/#eqnull) option

**Comment by madbook** [comment]
ah, right.  in that case, could you add a comment on the line above to state that it's intentional for that reason?

**Comment by dwick** [comment]
That's already apart of our jshint config.  I've added a note in the styleguide too: https://github.com/reddit/styleguide/pull/22

**Comment by madbook** [comment]
er, :fish: because I don't want to be blocking over a nit

**Comment by ajacksified** [comment]
:fish:

**Pull request merged**
